# Student Notebook
#### This notebook is for you to take notes and save directly to your Google drive and GITHUB.

Please upload your changes so you can review it later.

# Introduction to Python Basics I

In [1]:
import numpy as np

In [2]:
np.zeros(25)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(25)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
np.arange(25, 50+1)

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [11]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

###eye()

In [12]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### linspace()

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [22]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

###Random

### rand()

In [23]:
np.random.rand(2) #[0,1)] uniform distribution

array([0.86948134, 0.80704344])

In [24]:
np.random.rand(5,5)

array([[0.43546879, 0.6127321 , 0.60322192, 0.72868951, 0.37976895],
       [0.07404153, 0.90652219, 0.64613867, 0.72005996, 0.90832997],
       [0.3757751 , 0.40917366, 0.75050391, 0.72964705, 0.70645314],
       [0.00552142, 0.12627852, 0.75479194, 0.445693  , 0.29046331],
       [0.72809129, 0.20635709, 0.83199861, 0.26673929, 0.64491121]])

### randn

In [31]:
# standard normal distribution
np.random.randn(2)

array([-0.05063709, -1.04197459])

In [32]:
np.random.randn(5,5)

array([[ 1.13463458, -0.57787324, -0.24059575, -1.50488578, -0.69439381],
       [-1.02253845,  0.16618795,  0.41239034,  2.12000452, -1.09230828],
       [ 1.27396939, -1.7468854 ,  0.1547695 , -0.79886819, -0.33422831],
       [ 1.15005553, -1.05217668,  0.96349297,  0.69822022,  2.08955244],
       [-0.22133662, -1.25213258, -0.60434992,  0.58231019,  1.26621975]])

### randint()

In [38]:
np.random.randint(1,100)

53

In [39]:
np.random.randint(1,100,10)

array([73, 68, 20, 43, 64, 39, 88, 42, 77, 61])

## Arrays and Methods

In [41]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [85]:
ranarr = np.random.randint(0,50,10)
print(ranarr)

[37 30 30 12  1 25 40  6 14 49]


### reshape

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
#Ex7) Create a 3x3 matrix with value ranging fro
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
#Ex8) Create a 5x5 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
#Ex9) Use numpy to generate a random number between 0 and 1
np.random.rand(1)

array([0.39228141])

In [76]:
#Ex10) Use numpy to generate an array of 100 random numbers sampled from a standard distribution
np.random.randn(100)

array([-0.25349194,  0.39813769, -0.81706242,  0.43215529, -0.54586121,
       -0.26772154,  0.38556584,  1.25327234,  0.92534787, -0.56708383,
        0.74025833,  0.9180874 , -0.07349429,  1.87493146,  3.58478235,
        0.07327063, -0.02487859, -0.27836187, -1.28821534,  1.0105865 ,
       -0.62633218, -0.24575614, -0.1990164 , -1.57123223, -0.63970037,
        0.46040826, -0.02320088, -1.17562192, -0.82990889, -0.45653026,
       -0.99931969, -0.97567204,  2.1686092 ,  1.26850068,  0.46925119,
       -0.4943875 , -0.32892808,  0.89032985,  1.55974169,  0.09152634,
        0.95646434,  0.51803768, -0.72141985,  1.2810985 ,  1.49925296,
        0.88631339,  0.73702104, -1.7016747 ,  0.83006003, -1.01376765,
       -0.64034636,  0.25644087,  1.94678033, -0.19909268, -1.03239543,
        0.01815673,  1.20146755, -2.13041303,  0.90212266,  1.282679  ,
       -0.11426918,  1.25632424, -0.54199739,  0.69036596, -0.26398513,
        0.06150949,  0.570689  , -1.16204754, -0.58010491, -0.92

In [62]:
#Ex11) Create an array of 25 linearly spaced point between 0 and 1
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

### max, min methods

In [86]:
ranarr = np.random.randint(0,50,10)

In [87]:
ranarr

array([ 0,  3, 46, 35,  5, 33,  6, 45, 43, 46])

In [88]:
ranarr.max()

46

In [89]:
ranarr.min()

0

In [90]:
ranarr.argmax()

2

In [91]:
ranarr.argmin()

0