# Student Notebook
#### This notebook is for you to take notes and save directly to your Google drive and GITHUB.

Please upload your changes so you can review it later.

# Introduction to Python Basics I

In [ ]:
import numpy as np

In [ ]:
np.zeros(25)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(25)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(25, 50+1)

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

###eye()

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### linspace()

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

###Random

### rand()

In [ ]:
np.random.rand(2) #[0,1)] uniform distribution

array([0.86948134, 0.80704344])

In [ ]:
np.random.rand(5,5)

array([[0.43546879, 0.6127321 , 0.60322192, 0.72868951, 0.37976895],
       [0.07404153, 0.90652219, 0.64613867, 0.72005996, 0.90832997],
       [0.3757751 , 0.40917366, 0.75050391, 0.72964705, 0.70645314],
       [0.00552142, 0.12627852, 0.75479194, 0.445693  , 0.29046331],
       [0.72809129, 0.20635709, 0.83199861, 0.26673929, 0.64491121]])

### randn

In [ ]:
# standard normal distribution
np.random.randn(2)

array([-0.05063709, -1.04197459])

In [ ]:
np.random.randn(5,5)

array([[ 1.13463458, -0.57787324, -0.24059575, -1.50488578, -0.69439381],
       [-1.02253845,  0.16618795,  0.41239034,  2.12000452, -1.09230828],
       [ 1.27396939, -1.7468854 ,  0.1547695 , -0.79886819, -0.33422831],
       [ 1.15005553, -1.05217668,  0.96349297,  0.69822022,  2.08955244],
       [-0.22133662, -1.25213258, -0.60434992,  0.58231019,  1.26621975]])

### randint()

In [ ]:
np.random.randint(1,100)

53

In [ ]:
np.random.randint(1,100,10)

array([73, 68, 20, 43, 64, 39, 88, 42, 77, 61])

## Arrays and Methods

In [ ]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
ranarr = np.random.randint(0,50,10)
print(ranarr)

[23  3 38 19  4  4 48 20 30 16]


### reshape

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Ex7) Create a 3x3 matrix with value ranging fro
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Ex8) Create a 5x5 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Ex9) Use numpy to generate a random number between 0 and 1
np.random.rand(1)

array([0.39228141])

In [ ]:
#Ex10) Use numpy to generate an array of 100 random numbers sampled from a standard distribution
np.random.randn(100)

array([-0.25349194,  0.39813769, -0.81706242,  0.43215529, -0.54586121,
       -0.26772154,  0.38556584,  1.25327234,  0.92534787, -0.56708383,
        0.74025833,  0.9180874 , -0.07349429,  1.87493146,  3.58478235,
        0.07327063, -0.02487859, -0.27836187, -1.28821534,  1.0105865 ,
       -0.62633218, -0.24575614, -0.1990164 , -1.57123223, -0.63970037,
        0.46040826, -0.02320088, -1.17562192, -0.82990889, -0.45653026,
       -0.99931969, -0.97567204,  2.1686092 ,  1.26850068,  0.46925119,
       -0.4943875 , -0.32892808,  0.89032985,  1.55974169,  0.09152634,
        0.95646434,  0.51803768, -0.72141985,  1.2810985 ,  1.49925296,
        0.88631339,  0.73702104, -1.7016747 ,  0.83006003, -1.01376765,
       -0.64034636,  0.25644087,  1.94678033, -0.19909268, -1.03239543,
        0.01815673,  1.20146755, -2.13041303,  0.90212266,  1.282679  ,
       -0.11426918,  1.25632424, -0.54199739,  0.69036596, -0.26398513,
        0.06150949,  0.570689  , -1.16204754, -0.58010491, -0.92

In [ ]:
#Ex11) Create an array of 25 linearly spaced point between 0 and 1
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

### max, min methods

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
ranarr

array([ 0,  3, 46, 35,  5, 33,  6, 45, 43, 46])

In [ ]:
ranarr.max()

46

In [ ]:
ranarr.min()

0

In [ ]:
ranarr.argmax()

2

In [ ]:
ranarr.argmin()

0

### Shape

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(25)

In [ ]:
arr.shape

(25,)

In [ ]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

###dtype

In [ ]:
arr.dtype

dtype('int64')

## Numpy Indexing and Selection

In [ ]:
# create sample
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


### Bracket Indexing and Selection

In [ ]:
arr[8]

8

In [ ]:
#get values in a range [star:end]
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[-1]

10

In [ ]:
arr[-2]

9

### Broadcasting

In [ ]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_arr = arr[0:6]
print(slice_arr)

[0 1 2 3 4 5]


In [ ]:
slice_arr[:] = 99

In [ ]:
print(slice_arr)

[99 99 99 99 99 99]


In [ ]:
print(arr)

[99 99 99 99 99 99  6  7  8  9 10]


In [ ]:
#Ex1) Why it changed arr and slice_arr?

In [ ]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#Ex2) you have to replicate the following matrix using python code
#The variable name is "matrix":

In [ ]:
matrix = np.arange(1,50).reshape(7,7)
print(matrix)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


### Indexing a 2D array (matrix)

In [ ]:
# array_2d[row][col] = arr_2d[row,col]

In [ ]:
arr_2d = np.array((  [5,10,15],[20,25,30],[35,40,45]  ))

print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
#indexing a row
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[-1]

array([35, 40, 45])

In [ ]:
# array_2d[row][col]
arr_2d[1][0]

20

In [ ]:
# array_2d[row,col]
arr_2d[1,0]

20

In [ ]:
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
#2d array slicing
#top right corner of arr_2d with a shape of (2,2)

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [ ]:
#top row 
arr_2d[0,:]

array([ 5, 10, 15])

In [ ]:
matrix = np.arange(1,50).reshape(7,7)
print(matrix)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [ ]:
matrix = np.arange(1,50)
print(matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [ ]:
arr_2d = np.array((  [16,17,18,19,20,21],[23,24,25,26,27,28],[30,31,32,33,34,35],[37,38,39,40,41,42],[44,45,46,47,48,49]  ))

print(arr_2d)

[[16 17 18 19 20 21]
 [23 24 25 26 27 28]
 [30 31 32 33 34 35]
 [37 38 39 40 41 42]
 [44 45 46 47 48 49]]


In [ ]:
arr_2d[:2, 1:]

array([[17, 18, 19, 20, 21],
       [24, 25, 26, 27, 28]])

In [ ]:
arr_2d[1]

array([23, 24, 25, 26, 27, 28])

In [ ]:
arr_2d[1,3]

26

In [ ]:
arr_2d = np.array((  [22,23,24,25,26,27,28], [29,30,31,32,33,34,35]  ))

print(arr_2d)

[[22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]


In [ ]:
arr_2d = np.array((  [ 2], [ 9], [ 16]))

print(arr_2d)

[[ 2]
 [ 9]
 [16]]


In [ ]:
print(matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [ ]:
matrix[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
matrix = np.arange(1,50).reshape(7,7)
print(matrix)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [ ]:
matrix[2:, 1:]

array([[16, 17, 18, 19, 20, 21],
       [23, 24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34, 35],
       [37, 38, 39, 40, 41, 42],
       [44, 45, 46, 47, 48, 49]])

In [ ]:
matrix[3,4]

26

In [ ]:
matrix[:3,1]

array([ 2,  9, 16])

In [ ]:
matrix[3:5,:]

array([[22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

### Fancy Indexing

In [ ]:
arr2d = np.zeros((10,10))

In [ ]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr_length = arr2d.shape[1]
print(arr_length)

10


In [ ]:
for i in range(arr_length):
  arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[[ 2,4,6,8 ]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

### Selection

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Aritmetic

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

In [ ]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr) #arr.max

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
print(matrix)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [ ]:
## For next week.
Ex8) get the sum of all the values in the matrix

>>1225

In [ ]:
Ex9) Get the standard deviation of the values in matrix

>>14.1421...

In [ ]:
Ex10) Get the sum of all the colums in the matrix

>>array([154,161,168,175,189,196])

#Pandas

##Series

In [1]:
import numpy as np
import pandas as pd

### Creating a Series

In [2]:
lables = ['a','b','c'] #list of lables
my_list = [10,20,30] #list
arr = np.array([10,20,30]) #numpy array
d = {'a':10, 'b':20, 'c':30}

In [3]:
#using Lists
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(data=my_list, index=lables)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(my_list,lables)

a    10
b    20
c    30
dtype: int64

In [6]:
#using Numpy arrays
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(arr,lables)

a    10
b    20
c    30
dtype: int64

In [8]:
#using Dictionary
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Data in a Series

In [9]:
pd.Series(data = lables)

0    a
1    b
2    c
dtype: object

In [10]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

###Using an Index

In [11]:
ser1 = pd.Series([1,2,3,4],index=['Incheon','Suwon','Seoul','Busan'])
print(ser1)

Incheon    1
Suwon      2
Seoul      3
Busan      4
dtype: int64


In [12]:
ser2 = pd.Series([1,2,5,4],index = ['Incheon','Suwon','Seoul','Busan'])
print(ser2)

Incheon    1
Suwon      2
Seoul      5
Busan      4
dtype: int64


In [13]:
ser1['Incheon']

1

In [14]:
ser1 + ser2

Incheon    2
Suwon      4
Seoul      8
Busan      8
dtype: int64

## DataFrames

In [15]:
from numpy.random import randn
np.random.seed(101)


In [16]:
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split() )

In [17]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Selction and Indexing

In [18]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [19]:
#Pass a list of col names

df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [20]:
#I don't recommend this:

df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [21]:
type(df['W'])

pandas.core.series.Series

In [22]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [23]:
#create a new column
df['new'] = df['W'] + df['Y']

In [24]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [25]:
#removing columns
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [27]:
df.drop('new',axis=1,inplace=True)

In [28]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [29]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [30]:
#Selecting a row
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [31]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [32]:
#selecting a subset of rows and columns
df.loc['B','Y']

-0.8480769834036315

In [33]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional Selection

In [34]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [35]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [36]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [39]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [40]:
df[(df['W']>0) & (df['Y']>1) ]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

### More about index

In [41]:
#Peset index to a default values 0, 1, 2, 3

df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [42]:
newindex = 'Incheon Seoul Busan Jeju Suwon'.split()

In [44]:
df['Cities'] = newindex

In [45]:
df

W         X         Y         Z   Cities
A  2.706850  0.628133  0.907969  0.503826  Incheon
B  0.651118 -0.319318 -0.848077  0.605965    Seoul
C -2.018168  0.740122  0.528813 -0.589001    Busan
D  0.188695 -0.758872 -0.933237  0.955057     Jeju
E  0.190794  1.978757  2.605967  0.683509    Suwon

In [46]:
df.set_index('Cities')

W         X         Y         Z
Cities                                         
Incheon  2.706850  0.628133  0.907969  0.503826
Seoul    0.651118 -0.319318 -0.848077  0.605965
Busan   -2.018168  0.740122  0.528813 -0.589001
Jeju     0.188695 -0.758872 -0.933237  0.955057
Suwon    0.190794  1.978757  2.605967  0.683509

In [47]:
df

W         X         Y         Z   Cities
A  2.706850  0.628133  0.907969  0.503826  Incheon
B  0.651118 -0.319318 -0.848077  0.605965    Seoul
C -2.018168  0.740122  0.528813 -0.589001    Busan
D  0.188695 -0.758872 -0.933237  0.955057     Jeju
E  0.190794  1.978757  2.605967  0.683509    Suwon

In [48]:
df.set_index('Cities',inplace=True)

In [49]:
df

W         X         Y         Z
Cities                                         
Incheon  2.706850  0.628133  0.907969  0.503826
Seoul    0.651118 -0.319318 -0.848077  0.605965
Busan   -2.018168  0.740122  0.528813 -0.589001
Jeju     0.188695 -0.758872 -0.933237  0.955057
Suwon    0.190794  1.978757  2.605967  0.683509

### Multi-Index and Index Hierarchy

In [50]:
#Index levels

outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [51]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [59]:
df = pd.DataFrame(np.random.randn(6,2), index = hier_index, columns = ['A','B'])
df

A         B
G1 1  0.041460 -0.411055
   2 -0.771329  0.110477
   3 -0.804652  0.253548
G2 1  0.649148  0.358941
   2 -1.080471  0.902398
   3  0.161781  0.833029

In [63]:
df.loc['G1']

A         B
1  0.041460 -0.411055
2 -0.771329  0.110477
3 -0.804652  0.253548

In [64]:
df.loc['G1'].loc[1]

A    0.041460
B   -0.411055
Name: 1, dtype: float64

In [65]:
df.index.names

FrozenList([None, None])

In [66]:
df.index.names = ['Group', 'Num']

In [67]:
df

A         B
Group Num                    
G1    1    0.041460 -0.411055
      2   -0.771329  0.110477
      3   -0.804652  0.253548
G2    1    0.649148  0.358941
      2   -1.080471  0.902398
      3    0.161781  0.833029